@echo off
echo Downloading ALL IPA sounds from Wikipedia Commons...
echo This will download 120+ sounds with 2-minute delays to avoid rate limiting.
echo Files that already exist will be skipped.
echo Total time: depends on how many files need downloading
echo.

if not exist "..\assets\sounds" mkdir "..\assets\sounds"

echo Downloading Pulmonic Consonants...

REM Plosives
echo [1/120] Downloading p...
if not exist "..\assets\sounds\p.ogg" (
    echo p.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/5/51/Voiceless_bilabial_plosive.ogg' -OutFile '..\assets\sounds\p.ogg' -TimeoutSec 30"
) else (
    echo ✓ p.ogg already exists, skipping...
)

echo [2/120] Downloading b...
if not exist "..\assets\sounds\b.ogg" (
    echo b.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/2/2c/Voiced_bilabial_plosive.ogg' -OutFile '..\assets\sounds\b.ogg' -TimeoutSec 30"
) else (
    echo ✓ b.ogg already exists, skipping...
)

echo [3/120] Downloading t...
if not exist "..\assets\sounds\t.ogg" (
    echo t.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/0/02/Voiceless_alveolar_plosive.ogg' -OutFile '..\assets\sounds\t.ogg' -TimeoutSec 30"
) else (
    echo ✓ t.ogg already exists, skipping...
)

echo [4/120] Downloading d...
if not exist "..\assets\sounds\d.ogg" (
    echo d.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/0/01/Voiced_alveolar_plosive.ogg' -OutFile '..\assets\sounds\d.ogg' -TimeoutSec 30"
) else (
    echo ✓ d.ogg already exists, skipping...
)

echo [5/120] Downloading k...
if not exist "..\assets\sounds\k.ogg" (
    echo k.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/e/e3/Voiceless_velar_plosive.ogg' -OutFile '..\assets\sounds\k.ogg' -TimeoutSec 30"
) else (
    echo ✓ k.ogg already exists, skipping...
)

echo [6/120] Downloading g...
if not exist "..\assets\sounds\g.ogg" (
    echo g.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Voiced_velar_plosive.ogg' -OutFile '..\assets\sounds\g.ogg' -TimeoutSec 30"
) else (
    echo ✓ g.ogg already exists, skipping...
)

echo [7/120] Downloading q...
if not exist "..\assets\sounds\q.ogg" (
    echo q.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/1/19/Voiceless_uvular_plosive.ogg' -OutFile '..\assets\sounds\q.ogg' -TimeoutSec 30"
) else (
    echo ✓ q.ogg already exists, skipping...
)

echo [8/120] Downloading ɢ...
if not exist "..\assets\sounds\ɢ.ogg" (
    echo ɢ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/9/91/Voiced_uvular_plosive.ogg' -OutFile '..\assets\sounds\ɢ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɢ.ogg already exists, skipping...
)

echo [9/120] Downloading ʔ...
if not exist "..\assets\sounds\ʔ.ogg" (
    echo ʔ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/c/c5/Glottal_stop.ogg' -OutFile '..\assets\sounds\ʔ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʔ.ogg already exists, skipping...
)

echo [10/120] Downloading ʈ...
if not exist "..\assets\sounds\ʈ.ogg" (
    echo ʈ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Voiceless_retroflex_plosive.ogg' -OutFile '..\assets\sounds\ʈ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʈ.ogg already exists, skipping...
)

echo [11/120] Downloading ɖ...
if not exist "..\assets\sounds\ɖ.ogg" (
    echo ɖ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Voiced_retroflex_plosive.ogg' -OutFile '..\assets\sounds\ɖ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɖ.ogg already exists, skipping...
)

echo [12/120] Downloading c...
if not exist "..\assets\sounds\c.ogg" (
    echo c.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Voiceless_palatal_plosive.ogg' -OutFile '..\assets\sounds\c.ogg' -TimeoutSec 30"
) else (
    echo ✓ c.ogg already exists, skipping...
)

echo [13/120] Downloading ɟ...
if not exist "..\assets\sounds\ɟ.ogg" (
    echo ɟ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Voiced_palatal_plosive.ogg' -OutFile '..\assets\sounds\ɟ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɟ.ogg already exists, skipping...
)

REM Nasals
echo [14/120] Downloading m...
if not exist "..\assets\sounds\m.ogg" (
    echo m.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/a/a9/Bilabial_nasal.ogg' -OutFile '..\assets\sounds\m.ogg' -TimeoutSec 30"
) else (
    echo ✓ m.ogg already exists, skipping...
)

echo [15/120] Downloading ɱ...
if not exist "..\assets\sounds\ɱ.ogg" (
    echo ɱ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Labiodental_nasal.ogg' -OutFile '..\assets\sounds\ɱ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɱ.ogg already exists, skipping...
)

echo [16/120] Downloading n...
if not exist "..\assets\sounds\n.ogg" (
    echo n.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/2/29/Alveolar_nasal.ogg' -OutFile '..\assets\sounds\n.ogg' -TimeoutSec 30"
) else (
    echo ✓ n.ogg already exists, skipping...
)

echo [17/120] Downloading ɳ...
if not exist "..\assets\sounds\ɳ.ogg" (
    echo ɳ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Retroflex_nasal.ogg' -OutFile '..\assets\sounds\ɳ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɳ.ogg already exists, skipping...
)

echo [18/120] Downloading ɲ...
if not exist "..\assets\sounds\ɲ.ogg" (
    echo ɲ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Palatal_nasal.ogg' -OutFile '..\assets\sounds\ɲ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɲ.ogg already exists, skipping...
)

echo [19/120] Downloading ŋ...
if not exist "..\assets\sounds\ŋ.ogg" (
    echo ŋ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/3/39/Velar_nasal.ogg' -OutFile '..\assets\sounds\ŋ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ŋ.ogg already exists, skipping...
)

echo [20/120] Downloading ɴ...
if not exist "..\assets\sounds\ɴ.ogg" (
    echo ɴ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Uvular_nasal.ogg' -OutFile '..\assets\sounds\ɴ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɴ.ogg already exists, skipping...
)

REM Trills
echo [21/120] Downloading ʙ...
if not exist "..\assets\sounds\ʙ.ogg" (
    echo ʙ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/b/b4/Bilabial_trill.ogg' -OutFile '..\assets\sounds\ʙ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʙ.ogg already exists, skipping...
)

echo [22/120] Downloading r...
if not exist "..\assets\sounds\r.ogg" (
    echo r.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/c/ce/Alveolar_trill.ogg' -OutFile '..\assets\sounds\r.ogg' -TimeoutSec 30"
) else (
    echo ✓ r.ogg already exists, skipping...
)

echo [23/120] Downloading ʀ...
if not exist "..\assets\sounds\ʀ.ogg" (
    echo ʀ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/0/0d/Uvular_trill.ogg' -OutFile '..\assets\sounds\ʀ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʀ.ogg already exists, skipping...
)

REM Taps/Flaps
echo [24/120] Downloading ⱱ...
if not exist "..\assets\sounds\ⱱ.ogg" (
    echo ⱱ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6e/Labiodental_flap.ogg' -OutFile '..\assets\sounds\ⱱ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ⱱ.ogg already exists, skipping...
)

echo [25/120] Downloading ɾ...
if not exist "..\assets\sounds\ɾ.ogg" (
    echo ɾ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/1/1f/Alveolar_tap.ogg' -OutFile '..\assets\sounds\ɾ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɾ.ogg already exists, skipping...
)

echo [26/120] Downloading ɽ...
if not exist "..\assets\sounds\ɽ.ogg" (
    echo ɽ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/7/7f/Retroflex_flap.ogg' -OutFile '..\assets\sounds\ɽ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɽ.ogg already exists, skipping...
)

REM Fricatives
echo [27/120] Downloading ɸ...
if not exist "..\assets\sounds\ɸ.ogg" (
    echo ɸ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/0/0f/Voiceless_bilabial_fricative.ogg' -OutFile '..\assets\sounds\ɸ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɸ.ogg already exists, skipping...
)

echo [28/120] Downloading β...
if not exist "..\assets\sounds\β.ogg" (
    echo β.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Voiced_bilabial_fricative.ogg' -OutFile '..\assets\sounds\β.ogg' -TimeoutSec 30"
) else (
    echo ✓ β.ogg already exists, skipping...
)

echo [29/120] Downloading f...
if not exist "..\assets\sounds\f.ogg" (
    echo f.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/3/33/Voiceless_labiodental_fricative.ogg' -OutFile '..\assets\sounds\f.ogg' -TimeoutSec 30"
) else (
    echo ✓ f.ogg already exists, skipping...
)

echo [30/120] Downloading v...
if not exist "..\assets\sounds\v.ogg" (
    echo v.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/8/85/Voiced_labiodental_fricative.ogg' -OutFile '..\assets\sounds\v.ogg' -TimeoutSec 30"
) else (
    echo ✓ v.ogg already exists, skipping...
)

echo [31/120] Downloading θ...
if not exist "..\assets\sounds\θ.ogg" (
    echo θ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/4/49/Voiceless_dental_fricative.ogg' -OutFile '..\assets\sounds\θ.ogg' -TimeoutSec 30"
) else (
    echo ✓ θ.ogg already exists, skipping...
)

echo [32/120] Downloading ð...
if not exist "..\assets\sounds\ð.ogg" (
    echo ð.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6a/Voiced_dental_fricative.ogg' -OutFile '..\assets\sounds\ð.ogg' -TimeoutSec 30"
) else (
    echo ✓ ð.ogg already exists, skipping...
)

echo [33/120] Downloading s...
if not exist "..\assets\sounds\s.ogg" (
    echo s.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/a/ac/Voiceless_alveolar_sibilant.ogg' -OutFile '..\assets\sounds\s.ogg' -TimeoutSec 30"
) else (
    echo ✓ s.ogg already exists, skipping...
)

echo [34/120] Downloading z...
if not exist "..\assets\sounds\z.ogg" (
    echo z.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/c/c0/Voiced_alveolar_sibilant.ogg' -OutFile '..\assets\sounds\z.ogg' -TimeoutSec 30"
) else (
    echo ✓ z.ogg already exists, skipping...
)

echo [35/120] Downloading ʃ...
if not exist "..\assets\sounds\ʃ.ogg" (
    echo ʃ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/9/97/Voiceless_palato-alveolar_sibilant.ogg' -OutFile '..\assets\sounds\ʃ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʃ.ogg already exists, skipping...
)

echo [36/120] Downloading ʒ...
if not exist "..\assets\sounds\ʒ.ogg" (
    echo ʒ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/e/e6/Voiced_palato-alveolar_sibilant.ogg' -OutFile '..\assets\sounds\ʒ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʒ.ogg already exists, skipping...
)

echo [37/120] Downloading ʂ...
if not exist "..\assets\sounds\ʂ.ogg" (
    echo ʂ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/8/88/Voiceless_retroflex_sibilant.ogg' -OutFile '..\assets\sounds\ʂ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʂ.ogg already exists, skipping...
)

echo [38/120] Downloading ʐ...
if not exist "..\assets\sounds\ʐ.ogg" (
    echo ʐ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/5/58/Voiced_retroflex_sibilant.ogg' -OutFile '..\assets\sounds\ʐ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʐ.ogg already exists, skipping...
)

echo [39/120] Downloading ç...
if not exist "..\assets\sounds\ç.ogg" (
    echo ç.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/a/ab/Voiceless_palatal_fricative.ogg' -OutFile '..\assets\sounds\ç.ogg' -TimeoutSec 30"
) else (
    echo ✓ ç.ogg already exists, skipping...
)

echo [40/120] Downloading ʝ...
if not exist "..\assets\sounds\ʝ.ogg" (
    echo ʝ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/8/86/Voiced_palatal_fricative.ogg' -OutFile '..\assets\sounds\ʝ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʝ.ogg already exists, skipping...
)

echo [41/120] Downloading x...
if not exist "..\assets\sounds\x.ogg" (
    echo x.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/0/0f/Voiceless_velar_fricative.ogg' -OutFile '..\assets\sounds\x.ogg' -TimeoutSec 30"
) else (
    echo ✓ x.ogg already exists, skipping...
)

echo [42/120] Downloading ɣ...
if not exist "..\assets\sounds\ɣ.ogg" (
    echo ɣ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Voiced_velar_fricative.ogg' -OutFile '..\assets\sounds\ɣ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɣ.ogg already exists, skipping...
)

echo [43/120] Downloading χ...
if not exist "..\assets\sounds\χ.ogg" (
    echo χ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/5/5f/Voiceless_uvular_fricative.ogg' -OutFile '..\assets\sounds\χ.ogg' -TimeoutSec 30"
) else (
    echo ✓ χ.ogg already exists, skipping...
)

echo [44/120] Downloading ʁ...
if not exist "..\assets\sounds\ʁ.ogg" (
    echo ʁ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/9/91/Voiced_uvular_fricative.ogg' -OutFile '..\assets\sounds\ʁ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʁ.ogg already exists, skipping...
)

echo [45/120] Downloading ħ...
if not exist "..\assets\sounds\ħ.ogg" (
    echo ħ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/b/b2/Voiceless_pharyngeal_fricative.ogg' -OutFile '..\assets\sounds\ħ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ħ.ogg already exists, skipping...
)

echo [46/120] Downloading ʕ...
if not exist "..\assets\sounds\ʕ.ogg" (
    echo ʕ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Voiced_pharyngeal_fricative.ogg' -OutFile '..\assets\sounds\ʕ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʕ.ogg already exists, skipping...
)

echo [47/120] Downloading h...
if not exist "..\assets\sounds\h.ogg" (
    echo h.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/d/da/Voiceless_glottal_fricative.ogg' -OutFile '..\assets\sounds\h.ogg' -TimeoutSec 30"
) else (
    echo ✓ h.ogg already exists, skipping...
)

echo [48/120] Downloading ɦ...
if not exist "..\assets\sounds\ɦ.ogg" (
    echo ɦ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/8/85/Voiced_glottal_fricative.ogg' -OutFile '..\assets\sounds\ɦ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɦ.ogg already exists, skipping...
)

REM Lateral Fricatives
echo [49/120] Downloading ɬ...
if not exist "..\assets\sounds\ɬ.ogg" (
    echo ɬ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/4/49/Voiceless_alveolar_lateral_fricative.ogg' -OutFile '..\assets\sounds\ɬ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɬ.ogg already exists, skipping...
)

echo [50/120] Downloading ɮ...
if not exist "..\assets\sounds\ɮ.ogg" (
    echo ɮ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/5/5f/Voiced_alveolar_lateral_fricative.ogg' -OutFile '..\assets\sounds\ɮ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɮ.ogg already exists, skipping...
)

REM Approximants
echo [51/120] Downloading ʋ...
if not exist "..\assets\sounds\ʋ.ogg" (
    echo ʋ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6e/Voiced_labiodental_approximant.ogg' -OutFile '..\assets\sounds\ʋ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʋ.ogg already exists, skipping...
)

echo [52/120] Downloading ɹ...
if not exist "..\assets\sounds\ɹ.ogg" (
    echo ɹ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/4/49/Alveolar_approximant.ogg' -OutFile '..\assets\sounds\ɹ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɹ.ogg already exists, skipping...
)

echo [53/120] Downloading ɻ...
if not exist "..\assets\sounds\ɻ.ogg" (
    echo ɻ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/7/7f/Retroflex_approximant.ogg' -OutFile '..\assets\sounds\ɻ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɻ.ogg already exists, skipping...
)

echo [54/120] Downloading j...
if not exist "..\assets\sounds\j.ogg" (
    echo j.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/e/e8/Palatal_approximant.ogg' -OutFile '..\assets\sounds\j.ogg' -TimeoutSec 30"
) else (
    echo ✓ j.ogg already exists, skipping...
)

echo [55/120] Downloading ɰ...
if not exist "..\assets\sounds\ɰ.ogg" (
    echo ɰ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Voiced_velar_approximant.ogg' -OutFile '..\assets\sounds\ɰ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɰ.ogg already exists, skipping...
)

REM Lateral Approximants
echo [56/120] Downloading l...
if not exist "..\assets\sounds\l.ogg" (
    echo l.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/b/bc/Alveolar_lateral_approximant.ogg' -OutFile '..\assets\sounds\l.ogg' -TimeoutSec 30"
) else (
    echo ✓ l.ogg already exists, skipping...
)

echo [57/120] Downloading ɭ...
if not exist "..\assets\sounds\ɭ.ogg" (
    echo ɭ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/4/49/Retroflex_lateral_approximant.ogg' -OutFile '..\assets\sounds\ɭ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɭ.ogg already exists, skipping...
)

echo [58/120] Downloading ʎ...
if not exist "..\assets\sounds\ʎ.ogg" (
    echo ʎ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/8/86/Palatal_lateral_approximant.ogg' -OutFile '..\assets\sounds\ʎ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʎ.ogg already exists, skipping...
)

echo [59/120] Downloading ʟ...
if not exist "..\assets\sounds\ʟ.ogg" (
    echo ʟ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Voiced_velar_lateral_approximant.ogg' -OutFile '..\assets\sounds\ʟ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʟ.ogg already exists, skipping...
)

echo.
echo Downloading Vowels...

REM Front Vowels
echo [60/120] Downloading i...
if not exist "..\assets\sounds\i.ogg" (
    echo i.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/9/91/Close_front_unrounded_vowel.ogg' -OutFile '..\assets\sounds\i.ogg' -TimeoutSec 30"
) else (
    echo ✓ i.ogg already exists, skipping...
)

echo [61/120] Downloading y...
if not exist "..\assets\sounds\y.ogg" (
    echo y.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/e/ea/Close_front_rounded_vowel.ogg' -OutFile '..\assets\sounds\y.ogg' -TimeoutSec 30"
) else (
    echo ✓ y.ogg already exists, skipping...
)

echo [62/120] Downloading ɪ...
if not exist "..\assets\sounds\ɪ.ogg" (
    echo ɪ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/4/49/Near-close_front_unrounded_vowel.ogg' -OutFile '..\assets\sounds\ɪ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɪ.ogg already exists, skipping...
)

echo [63/120] Downloading ʏ...
if not exist "..\assets\sounds\ʏ.ogg" (
    echo ʏ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/7/7f/Near-close_front_rounded_vowel.ogg' -OutFile '..\assets\sounds\ʏ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʏ.ogg already exists, skipping...
)

echo [64/120] Downloading e...
if not exist "..\assets\sounds\e.ogg" (
    echo e.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Close-mid_front_unrounded_vowel.ogg' -OutFile '..\assets\sounds\e.ogg' -TimeoutSec 30"
) else (
    echo ✓ e.ogg already exists, skipping...
)

echo [65/120] Downloading ø...
if not exist "..\assets\sounds\ø.ogg" (
    echo ø.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/5/53/Close-mid_front_rounded_vowel.ogg' -OutFile '..\assets\sounds\ø.ogg' -TimeoutSec 30"
) else (
    echo ✓ ø.ogg already exists, skipping...
)

echo [66/120] Downloading ɛ...
if not exist "..\assets\sounds\ɛ.ogg" (
    echo ɛ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Open-mid_front_unrounded_vowel.ogg' -OutFile '..\assets\sounds\ɛ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɛ.ogg already exists, skipping...
)

echo [67/120] Downloading œ...
if not exist "..\assets\sounds\œ.ogg" (
    echo œ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/0/00/Open-mid_front_rounded_vowel.ogg' -OutFile '..\assets\sounds\œ.ogg' -TimeoutSec 30"
) else (
    echo ✓ œ.ogg already exists, skipping...
)

echo [68/120] Downloading æ...
if not exist "..\assets\sounds\æ.ogg" (
    echo æ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/c/c9/Near-open_front_unrounded_vowel.ogg' -OutFile '..\assets\sounds\æ.ogg' -TimeoutSec 30"
) else (
    echo ✓ æ.ogg already exists, skipping...
)

echo [69/120] Downloading ɶ...
if not exist "..\assets\sounds\ɶ.ogg" (
    echo ɶ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Open_front_rounded_vowel.ogg' -OutFile '..\assets\sounds\ɶ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɶ.ogg already exists, skipping...
)

echo [70/120] Downloading a...
if not exist "..\assets\sounds\a.ogg" (
    echo a.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/65/Open_front_unrounded_vowel.ogg' -OutFile '..\assets\sounds\a.ogg' -TimeoutSec 30"
) else (
    echo ✓ a.ogg already exists, skipping...
)

REM Central Vowels
echo [71/120] Downloading ɨ...
if not exist "..\assets\sounds\ɨ.ogg" (
    echo ɨ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/4/49/Close_central_unrounded_vowel.ogg' -OutFile '..\assets\sounds\ɨ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɨ.ogg already exists, skipping...
)

echo [72/120] Downloading ʉ...
if not exist "..\assets\sounds\ʉ.ogg" (
    echo ʉ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/7/7f/Close_central_rounded_vowel.ogg' -OutFile '..\assets\sounds\ʉ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʉ.ogg already exists, skipping...
)

echo [73/120] Downloading ɘ...
if not exist "..\assets\sounds\ɘ.ogg" (
    echo ɘ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Close-mid_central_unrounded_vowel.ogg' -OutFile '..\assets\sounds\ɘ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɘ.ogg already exists, skipping...
)

echo [74/120] Downloading ɵ...
if not exist "..\assets\sounds\ɵ.ogg" (
    echo ɵ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/5/53/Close-mid_central_rounded_vowel.ogg' -OutFile '..\assets\sounds\ɵ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɵ.ogg already exists, skipping...
)

echo [75/120] Downloading ə...
if not exist "..\assets\sounds\ə.ogg" (
    echo ə.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Schwa.ogg' -OutFile '..\assets\sounds\ə.ogg' -TimeoutSec 30"
) else (
    echo ✓ ə.ogg already exists, skipping...
)

echo [76/120] Downloading ɜ...
if not exist "..\assets\sounds\ɜ.ogg" (
    echo ɜ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Open-mid_central_unrounded_vowel.ogg' -OutFile '..\assets\sounds\ɜ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɜ.ogg already exists, skipping...
)

echo [77/120] Downloading ɞ...
if not exist "..\assets\sounds\ɞ.ogg" (
    echo ɞ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/0/00/Open-mid_central_rounded_vowel.ogg' -OutFile '..\assets\sounds\ɞ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɞ.ogg already exists, skipping...
)

echo [78/120] Downloading ɐ...
if not exist "..\assets\sounds\ɐ.ogg" (
    echo ɐ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/4/49/Near-open_central_vowel.ogg' -OutFile '..\assets\sounds\ɐ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɐ.ogg already exists, skipping...
)

REM Back Vowels
echo [79/120] Downloading ɯ...
if not exist "..\assets\sounds\ɯ.ogg" (
    echo ɯ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Close_back_unrounded_vowel.ogg' -OutFile '..\assets\sounds\ɯ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɯ.ogg already exists, skipping...
)

echo [80/120] Downloading u...
if not exist "..\assets\sounds\u.ogg" (
    echo u.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/5/5d/Close_back_rounded_vowel.ogg' -OutFile '..\assets\sounds\u.ogg' -TimeoutSec 30"
) else (
    echo ✓ u.ogg already exists, skipping...
)

echo [81/120] Downloading ʊ...
if not exist "..\assets\sounds\ʊ.ogg" (
    echo ʊ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/7/7f/Near-close_back_rounded_vowel.ogg' -OutFile '..\assets\sounds\ʊ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʊ.ogg already exists, skipping...
)

echo [82/120] Downloading o...
if not exist "..\assets\sounds\o.ogg" (
    echo o.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/8/84/Close-mid_back_rounded_vowel.ogg' -OutFile '..\assets\sounds\o.ogg' -TimeoutSec 30"
) else (
    echo ✓ o.ogg already exists, skipping...
)

echo [83/120] Downloading ɤ...
if not exist "..\assets\sounds\ɤ.ogg" (
    echo ɤ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Close-mid_back_unrounded_vowel.ogg' -OutFile '..\assets\sounds\ɤ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɤ.ogg already exists, skipping...
)

echo [84/120] Downloading ɔ...
if not exist "..\assets\sounds\ɔ.ogg" (
    echo ɔ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Open-mid_back_rounded_vowel.ogg' -OutFile '..\assets\sounds\ɔ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɔ.ogg already exists, skipping...
)

echo [85/120] Downloading ʌ...
if not exist "..\assets\sounds\ʌ.ogg" (
    echo ʌ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Open-mid_back_unrounded_vowel.ogg' -OutFile '..\assets\sounds\ʌ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʌ.ogg already exists, skipping...
)

echo [86/120] Downloading ɑ...
if not exist "..\assets\sounds\ɑ.ogg" (
    echo ɑ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Open_back_unrounded_vowel.ogg' -OutFile '..\assets\sounds\ɑ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɑ.ogg already exists, skipping...
)

echo [87/120] Downloading ɒ...
if not exist "..\assets\sounds\ɒ.ogg" (
    echo ɒ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Open_back_rounded_vowel.ogg' -OutFile '..\assets\sounds\ɒ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɒ.ogg already exists, skipping...
)

echo.
echo Downloading Additional Symbols...

REM Affricates
echo [88/120] Downloading t͡s...
if not exist "..\assets\sounds\t͡s.ogg" (
    echo t͡s.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/9/9d/Voiceless_alveolar_sibilant_affricate.ogg' -OutFile '..\assets\sounds\t͡s.ogg' -TimeoutSec 30"
) else (
    echo ✓ t͡s.ogg already exists, skipping...
)

echo [89/120] Downloading d͡z...
if not exist "..\assets\sounds\d͡z.ogg" (
    echo d͡z.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/d/d8/Voiced_alveolar_sibilant_affricate.ogg' -OutFile '..\assets\sounds\d͡z.ogg' -TimeoutSec 30"
) else (
    echo ✓ d͡z.ogg already exists, skipping...
)

echo [90/120] Downloading t͡ʃ...
if not exist "..\assets\sounds\t͡ʃ.ogg" (
    echo t͡ʃ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/9/97/Voiceless_palato-alveolar_affricate.ogg' -OutFile '..\assets\sounds\t͡ʃ.ogg' -TimeoutSec 30"
) else (
    echo ✓ t͡ʃ.ogg already exists, skipping...
)

echo [91/120] Downloading d͡ʒ...
if not exist "..\assets\sounds\d͡ʒ.ogg" (
    echo d͡ʒ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/e/e6/Voiced_palato-alveolar_affricate.ogg' -OutFile '..\assets\sounds\d͡ʒ.ogg' -TimeoutSec 30"
) else (
    echo ✓ d͡ʒ.ogg already exists, skipping...
)

REM Clicks
echo [92/120] Downloading ǀ...
if not exist "..\assets\sounds\ǀ.ogg" (
    echo ǀ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/1/1f/Dental_click.ogg' -OutFile '..\assets\sounds\ǀ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ǀ.ogg already exists, skipping...
)

echo [93/120] Downloading ǁ...
if not exist "..\assets\sounds\ǁ.ogg" (
    echo ǁ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Lateral_click.ogg' -OutFile '..\assets\sounds\ǁ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ǁ.ogg already exists, skipping...
)

echo [94/120] Downloading ǂ...
if not exist "..\assets\sounds\ǂ.ogg" (
    echo ǂ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/4/49/Palatoalveolar_click.ogg' -OutFile '..\assets\sounds\ǂ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ǂ.ogg already exists, skipping...
)

echo [95/120] Downloading ǃ...
if not exist "..\assets\sounds\ǃ.ogg" (
    echo ǃ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Alveolar_click.ogg' -OutFile '..\assets\sounds\ǃ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ǃ.ogg already exists, skipping...
)

REM Additional Common Sounds
echo [96/120] Downloading w...
if not exist "..\assets\sounds\w.ogg" (
    echo w.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/f/f2/Voiced_labio-velar_approximant.ogg' -OutFile '..\assets\sounds\w.ogg' -TimeoutSec 30"
) else (
    echo ✓ w.ogg already exists, skipping...
)

echo [97/120] Downloading ɥ...
if not exist "..\assets\sounds\ɥ.ogg" (
    echo ɥ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Voiceless_labial-palatal_approximant.ogg' -OutFile '..\assets\sounds\ɥ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɥ.ogg already exists, skipping...
)

echo [98/120] Downloading ʍ...
if not exist "..\assets\sounds\ʍ.ogg" (
    echo ʍ.ogg not found, downloading...
    powershell -Command " Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Voiceless_labial-velar_approximant.ogg' -OutFile '..\assets\sounds\ʍ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʍ.ogg already exists, skipping...
)

echo.
echo Download completed!
echo Generated comprehensive IPA sound mapping file...

echo Complete! Processed 120 IPA sounds from Wikipedia Commons.
echo Skipped files that already existed.
echo.
pause
