@echo off
echo Downloading ALL IPA sounds from Wikipedia Commons...
echo This will download 100+ sounds with 2-minute delays to avoid rate limiting.
echo Files that already exist will be skipped.
echo Total time: depends on how many files need downloading
echo.

if not exist "..\assets\sounds" mkdir "..\assets\sounds"

echo Downloading Pulmonic Consonants...

REM Plosives
echo [1/100] Downloading p...
if not exist "..\assets\sounds\p.ogg" (
    echo p.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/5/51/Voiceless_bilabial_plosive.ogg' -OutFile '..\assets\sounds\p.ogg' -TimeoutSec 30"
) else (
    echo ✓ p.ogg already exists, skipping...
)

echo [2/100] Downloading b...
if not exist "..\assets\sounds\b.ogg" (
    echo b.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/2/2c/Voiced_bilabial_plosive.ogg' -OutFile '..\assets\sounds\b.ogg' -TimeoutSec 30"
) else (
    echo ✓ b.ogg already exists, skipping...
)

echo [3/100] Downloading t...
if not exist "..\assets\sounds\t.ogg" (
    echo t.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/0/02/Voiceless_alveolar_plosive.ogg' -OutFile '..\assets\sounds\t.ogg' -TimeoutSec 30"
) else (
    echo ✓ t.ogg already exists, skipping...
)

echo [4/100] Downloading d...
if not exist "..\assets\sounds\d.ogg" (
    echo d.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/0/01/Voiced_alveolar_plosive.ogg' -OutFile '..\assets\sounds\d.ogg' -TimeoutSec 30"
) else (
    echo ✓ d.ogg already exists, skipping...
)

echo [5/100] Downloading k...
if not exist "..\assets\sounds\k.ogg" (
    echo k.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/e/e3/Voiceless_velar_plosive.ogg' -OutFile '..\assets\sounds\k.ogg' -TimeoutSec 30"
) else (
    echo ✓ k.ogg already exists, skipping...
)

echo [6/100] Downloading g...
if not exist "..\assets\sounds\g.ogg" (
    echo g.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Voiced_velar_plosive.ogg' -OutFile '..\assets\sounds\g.ogg' -TimeoutSec 30"
) else (
    echo ✓ g.ogg already exists, skipping...
)

echo [7/100] Downloading q...
if not exist "..\assets\sounds\q.ogg" (
    echo q.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/1/19/Voiceless_uvular_plosive.ogg' -OutFile '..\assets\sounds\q.ogg' -TimeoutSec 30"
) else (
    echo ✓ q.ogg already exists, skipping...
)

echo [8/100] Downloading ɢ...
if not exist "..\assets\sounds\ɢ.ogg" (
    echo ɢ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/9/91/Voiced_uvular_plosive.ogg' -OutFile '..\assets\sounds\ɢ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɢ.ogg already exists, skipping...
)

echo [9/100] Downloading ʔ...
if not exist "..\assets\sounds\ʔ.ogg" (
    echo ʔ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/c/c5/Glottal_stop.ogg' -OutFile '..\assets\sounds\ʔ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʔ.ogg already exists, skipping...
)

REM Nasals
echo [10/100] Downloading m...
if not exist "..\assets\sounds\m.ogg" (
    echo m.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/a/a9/Bilabial_nasal.ogg' -OutFile '..\assets\sounds\m.ogg' -TimeoutSec 30"
) else (
    echo ✓ m.ogg already exists, skipping...
)

echo [11/100] Downloading ɱ...
if not exist "..\assets\sounds\ɱ.ogg" (
    echo ɱ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Labiodental_nasal.ogg' -OutFile '..\assets\sounds\ɱ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɱ.ogg already exists, skipping...
)

echo [12/100] Downloading n...
if not exist "..\assets\sounds\n.ogg" (
    echo n.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/2/29/Alveolar_nasal.ogg' -OutFile '..\assets\sounds\n.ogg' -TimeoutSec 30"
) else (
    echo ✓ n.ogg already exists, skipping...
)

echo [13/100] Downloading ɳ...
if not exist "..\assets\sounds\ɳ.ogg" (
    echo ɳ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Retroflex_nasal.ogg' -OutFile '..\assets\sounds\ɳ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɳ.ogg already exists, skipping...
)

echo [14/100] Downloading ɲ...
if not exist "..\assets\sounds\ɲ.ogg" (
    echo ɲ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Palatal_nasal.ogg' -OutFile '..\assets\sounds\ɲ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɲ.ogg already exists, skipping...
)

echo [15/100] Downloading ŋ...
if not exist "..\assets\sounds\ŋ.ogg" (
    echo ŋ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/3/39/Velar_nasal.ogg' -OutFile '..\assets\sounds\ŋ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ŋ.ogg already exists, skipping...
)

echo [16/100] Downloading ɴ...
if not exist "..\assets\sounds\ɴ.ogg" (
    echo ɴ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Uvular_nasal.ogg' -OutFile '..\assets\sounds\ɴ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɴ.ogg already exists, skipping...
)

REM Trills
echo [17/100] Downloading ʙ...
if not exist "..\assets\sounds\ʙ.ogg" (
    echo ʙ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/b/b4/Bilabial_trill.ogg' -OutFile '..\assets\sounds\ʙ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʙ.ogg already exists, skipping...
)

echo [18/100] Downloading r...
if not exist "..\assets\sounds\r.ogg" (
    echo r.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/c/ce/Alveolar_trill.ogg' -OutFile '..\assets\sounds\r.ogg' -TimeoutSec 30"
) else (
    echo ✓ r.ogg already exists, skipping...
)

echo [19/100] Downloading ʀ...
if not exist "..\assets\sounds\ʀ.ogg" (
    echo ʀ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/0/0d/Uvular_trill.ogg' -OutFile '..\assets\sounds\ʀ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʀ.ogg already exists, skipping...
)

REM Taps/Flaps
echo [20/100] Downloading ⱱ...
if not exist "..\assets\sounds\ⱱ.ogg" (
    echo ⱱ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6e/Labiodental_flap.ogg' -OutFile '..\assets\sounds\ⱱ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ⱱ.ogg already exists, skipping...
)

echo [21/100] Downloading ɾ...
if not exist "..\assets\sounds\ɾ.ogg" (
    echo ɾ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/1/1f/Alveolar_tap.ogg' -OutFile '..\assets\sounds\ɾ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɾ.ogg already exists, skipping...
)

echo [22/100] Downloading ɽ...
if not exist "..\assets\sounds\ɽ.ogg" (
    echo ɽ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/7/7f/Retroflex_flap.ogg' -OutFile '..\assets\sounds\ɽ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɽ.ogg already exists, skipping...
)

REM Fricatives
echo [23/100] Downloading ɸ...
if not exist "..\assets\sounds\ɸ.ogg" (
    echo ɸ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/0/0f/Voiceless_bilabial_fricative.ogg' -OutFile '..\assets\sounds\ɸ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɸ.ogg already exists, skipping...
)

echo [24/100] Downloading β...
if not exist "..\assets\sounds\β.ogg" (
    echo β.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Voiced_bilabial_fricative.ogg' -OutFile '..\assets\sounds\β.ogg' -TimeoutSec 30"
) else (
    echo ✓ β.ogg already exists, skipping...
)

echo [25/100] Downloading f...
if not exist "..\assets\sounds\f.ogg" (
    echo f.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/3/33/Voiceless_labiodental_fricative.ogg' -OutFile '..\assets\sounds\f.ogg' -TimeoutSec 30"
) else (
    echo ✓ f.ogg already exists, skipping...
)

echo [26/100] Downloading v...
if not exist "..\assets\sounds\v.ogg" (
    echo v.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/8/85/Voiced_labiodental_fricative.ogg' -OutFile '..\assets\sounds\v.ogg' -TimeoutSec 30"
) else (
    echo ✓ v.ogg already exists, skipping...
)

echo [27/100] Downloading θ...
if not exist "..\assets\sounds\θ.ogg" (
    echo θ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/4/49/Voiceless_dental_fricative.ogg' -OutFile '..\assets\sounds\θ.ogg' -TimeoutSec 30"
) else (
    echo ✓ θ.ogg already exists, skipping...
)

echo [28/100] Downloading ð...
if not exist "..\assets\sounds\ð.ogg" (
    echo ð.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6a/Voiced_dental_fricative.ogg' -OutFile '..\assets\sounds\ð.ogg' -TimeoutSec 30"
) else (
    echo ✓ ð.ogg already exists, skipping...
)

echo [29/100] Downloading s...
if not exist "..\assets\sounds\s.ogg" (
    echo s.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/a/ac/Voiceless_alveolar_sibilant.ogg' -OutFile '..\assets\sounds\s.ogg' -TimeoutSec 30"
) else (
    echo ✓ s.ogg already exists, skipping...
)

echo [30/100] Downloading z...
if not exist "..\assets\sounds\z.ogg" (
    echo z.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/c/c0/Voiced_alveolar_sibilant.ogg' -OutFile '..\assets\sounds\z.ogg' -TimeoutSec 30"
) else (
    echo ✓ z.ogg already exists, skipping...
)

echo [31/100] Downloading ʃ...
if not exist "..\assets\sounds\ʃ.ogg" (
    echo ʃ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/9/97/Voiceless_palato-alveolar_sibilant.ogg' -OutFile '..\assets\sounds\ʃ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʃ.ogg already exists, skipping...
)

echo [32/100] Downloading ʒ...
if not exist "..\assets\sounds\ʒ.ogg" (
    echo ʒ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/e/e6/Voiced_palato-alveolar_sibilant.ogg' -OutFile '..\assets\sounds\ʒ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʒ.ogg already exists, skipping...
)

echo [33/100] Downloading ʂ...
if not exist "..\assets\sounds\ʂ.ogg" (
    echo ʂ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/8/88/Voiceless_retroflex_sibilant.ogg' -OutFile '..\assets\sounds\ʂ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʂ.ogg already exists, skipping...
)

echo [34/100] Downloading ʐ...
if not exist "..\assets\sounds\ʐ.ogg" (
    echo ʐ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/5/58/Voiced_retroflex_sibilant.ogg' -OutFile '..\assets\sounds\ʐ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʐ.ogg already exists, skipping...
)

echo [35/100] Downloading ç...
if not exist "..\assets\sounds\ç.ogg" (
    echo ç.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/a/ab/Voiceless_palatal_fricative.ogg' -OutFile '..\assets\sounds\ç.ogg' -TimeoutSec 30"
) else (
    echo ✓ ç.ogg already exists, skipping...
)

echo [36/100] Downloading ʝ...
if not exist "..\assets\sounds\ʝ.ogg" (
    echo ʝ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/8/86/Voiced_palatal_fricative.ogg' -OutFile '..\assets\sounds\ʝ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʝ.ogg already exists, skipping...
)

echo [37/100] Downloading x...
if not exist "..\assets\sounds\x.ogg" (
    echo x.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/0/0f/Voiceless_velar_fricative.ogg' -OutFile '..\assets\sounds\x.ogg' -TimeoutSec 30"
) else (
    echo ✓ x.ogg already exists, skipping...
)

echo [38/100] Downloading ɣ...
if not exist "..\assets\sounds\ɣ.ogg" (
    echo ɣ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Voiced_velar_fricative.ogg' -OutFile '..\assets\sounds\ɣ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɣ.ogg already exists, skipping...
)

echo [39/100] Downloading χ...
if not exist "..\assets\sounds\χ.ogg" (
    echo χ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/5/5f/Voiceless_uvular_fricative.ogg' -OutFile '..\assets\sounds\χ.ogg' -TimeoutSec 30"
) else (
    echo ✓ χ.ogg already exists, skipping...
)

echo [40/100] Downloading ʁ...
if not exist "..\assets\sounds\ʁ.ogg" (
    echo ʁ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/9/91/Voiced_uvular_fricative.ogg' -OutFile '..\assets\sounds\ʁ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʁ.ogg already exists, skipping...
)

echo [41/100] Downloading ħ...
if not exist "..\assets\sounds\ħ.ogg" (
    echo ħ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/b/b2/Voiceless_pharyngeal_fricative.ogg' -OutFile '..\assets\sounds\ħ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ħ.ogg already exists, skipping...
)

echo [42/100] Downloading ʕ...
if not exist "..\assets\sounds\ʕ.ogg" (
    echo ʕ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Voiced_pharyngeal_fricative.ogg' -OutFile '..\assets\sounds\ʕ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʕ.ogg already exists, skipping...
)

echo [43/100] Downloading h...
if not exist "..\assets\sounds\h.ogg" (
    echo h.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/d/da/Voiceless_glottal_fricative.ogg' -OutFile '..\assets\sounds\h.ogg' -TimeoutSec 30"
) else (
    echo ✓ h.ogg already exists, skipping...
)

echo [44/100] Downloading ɦ...
if not exist "..\assets\sounds\ɦ.ogg" (
    echo ɦ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/8/85/Voiced_glottal_fricative.ogg' -OutFile '..\assets\sounds\ɦ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɦ.ogg already exists, skipping...
)

REM Lateral Fricatives
echo [41/100] Downloading ɬ...
if not exist "..\assets\sounds\ɬ.ogg" (
    echo ɬ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/4/49/Voiceless_alveolar_lateral_fricative.ogg' -OutFile '..\assets\sounds\ɬ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɬ.ogg already exists, skipping...
)

echo [42/100] Downloading ɮ...
if not exist "..\assets\sounds\ɮ.ogg" (
    echo ɮ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/5/5f/Voiced_alveolar_lateral_fricative.ogg' -OutFile '..\assets\sounds\ɮ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɮ.ogg already exists, skipping...
)

REM Approximants
echo [43/100] Downloading ʋ...
if not exist "..\assets\sounds\ʋ.ogg" (
    echo ʋ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6e/Voiced_labiodental_approximant.ogg' -OutFile '..\assets\sounds\ʋ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʋ.ogg already exists, skipping...
)

echo [44/100] Downloading ɹ...
if not exist "..\assets\sounds\ɹ.ogg" (
    echo ɹ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/4/49/Alveolar_approximant.ogg' -OutFile '..\assets\sounds\ɹ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɹ.ogg already exists, skipping...
)

echo [45/100] Downloading ɻ...
if not exist "..\assets\sounds\ɻ.ogg" (
    echo ɻ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/7/7f/Retroflex_approximant.ogg' -OutFile '..\assets\sounds\ɻ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɻ.ogg already exists, skipping...
)

echo [46/100] Downloading j...
if not exist "..\assets\sounds\j.ogg" (
    echo j.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/e/e8/Palatal_approximant.ogg' -OutFile '..\assets\sounds\j.ogg' -TimeoutSec 30"
) else (
    echo ✓ j.ogg already exists, skipping...
)

echo [47/100] Downloading ɰ...
if not exist "..\assets\sounds\ɰ.ogg" (
    echo ɰ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Voiced_velar_approximant.ogg' -OutFile '..\assets\sounds\ɰ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɰ.ogg already exists, skipping...
)

REM Lateral Approximants
echo [48/100] Downloading l...
if not exist "..\assets\sounds\l.ogg" (
    echo l.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/b/bc/Alveolar_lateral_approximant.ogg' -OutFile '..\assets\sounds\l.ogg' -TimeoutSec 30"
) else (
    echo ✓ l.ogg already exists, skipping...
)

echo [49/100] Downloading ɭ...
if not exist "..\assets\sounds\ɭ.ogg" (
    echo ɭ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/4/49/Retroflex_lateral_approximant.ogg' -OutFile '..\assets\sounds\ɭ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɭ.ogg already exists, skipping...
)

echo [50/100] Downloading ʎ...
if not exist "..\assets\sounds\ʎ.ogg" (
    echo ʎ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/8/86/Palatal_lateral_approximant.ogg' -OutFile '..\assets\sounds\ʎ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʎ.ogg already exists, skipping...
)

echo [51/100] Downloading ʟ...
if not exist "..\assets\sounds\ʟ.ogg" (
    echo ʟ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Voiced_velar_lateral_approximant.ogg' -OutFile '..\assets\sounds\ʟ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʟ.ogg already exists, skipping...
)

echo.
echo Downloading Vowels...

REM Front Vowels
echo [52/100] Downloading i...
if not exist "..\assets\sounds\i.ogg" (
    echo i.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/9/91/Close_front_unrounded_vowel.ogg' -OutFile '..\assets\sounds\i.ogg' -TimeoutSec 30"
) else (
    echo ✓ i.ogg already exists, skipping...
)

echo [53/100] Downloading y...
if not exist "..\assets\sounds\y.ogg" (
    echo y.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/e/ea/Close_front_rounded_vowel.ogg' -OutFile '..\assets\sounds\y.ogg' -TimeoutSec 30"
) else (
    echo ✓ y.ogg already exists, skipping...
)

echo [54/100] Downloading ɪ...
if not exist "..\assets\sounds\ɪ.ogg" (
    echo ɪ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/4/49/Near-close_front_unrounded_vowel.ogg' -OutFile '..\assets\sounds\ɪ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɪ.ogg already exists, skipping...
)

echo [55/100] Downloading ʏ...
if not exist "..\assets\sounds\ʏ.ogg" (
    echo ʏ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/7/7f/Near-close_front_rounded_vowel.ogg' -OutFile '..\assets\sounds\ʏ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʏ.ogg already exists, skipping...
)

echo [56/100] Downloading e...
if not exist "..\assets\sounds\e.ogg" (
    echo e.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Close-mid_front_unrounded_vowel.ogg' -OutFile '..\assets\sounds\e.ogg' -TimeoutSec 30"
) else (
    echo ✓ e.ogg already exists, skipping...
)

echo [57/100] Downloading ø...
if not exist "..\assets\sounds\ø.ogg" (
    echo ø.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/5/53/Close-mid_front_rounded_vowel.ogg' -OutFile '..\assets\sounds\ø.ogg' -TimeoutSec 30"
) else (
    echo ✓ ø.ogg already exists, skipping...
)

echo [58/100] Downloading ɛ...
if not exist "..\assets\sounds\ɛ.ogg" (
    echo ɛ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Open-mid_front_unrounded_vowel.ogg' -OutFile '..\assets\sounds\ɛ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɛ.ogg already exists, skipping...
)

echo [59/100] Downloading œ...
if not exist "..\assets\sounds\œ.ogg" (
    echo œ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/0/00/Open-mid_front_rounded_vowel.ogg' -OutFile '..\assets\sounds\œ.ogg' -TimeoutSec 30"
) else (
    echo ✓ œ.ogg already exists, skipping...
)

echo [60/100] Downloading æ...
if not exist "..\assets\sounds\æ.ogg" (
    echo æ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/c/c9/Near-open_front_unrounded_vowel.ogg' -OutFile '..\assets\sounds\æ.ogg' -TimeoutSec 30"
) else (
    echo ✓ æ.ogg already exists, skipping...
)

echo [61/100] Downloading ɶ...
if not exist "..\assets\sounds\ɶ.ogg" (
    echo ɶ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Open_front_rounded_vowel.ogg' -OutFile '..\assets\sounds\ɶ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɶ.ogg already exists, skipping...
)

echo [62/100] Downloading a...
if not exist "..\assets\sounds\a.ogg" (
    echo a.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/65/Open_front_unrounded_vowel.ogg' -OutFile '..\assets\sounds\a.ogg' -TimeoutSec 30"
) else (
    echo ✓ a.ogg already exists, skipping...
)

REM Central Vowels
echo [63/100] Downloading ɨ...
if not exist "..\assets\sounds\ɨ.ogg" (
    echo ɨ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/4/49/Close_central_unrounded_vowel.ogg' -OutFile '..\assets\sounds\ɨ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɨ.ogg already exists, skipping...
)

echo [64/100] Downloading ʉ...
if not exist "..\assets\sounds\ʉ.ogg" (
    echo ʉ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/7/7f/Close_central_rounded_vowel.ogg' -OutFile '..\assets\sounds\ʉ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʉ.ogg already exists, skipping...
)

echo [65/100] Downloading ɘ...
if not exist "..\assets\sounds\ɘ.ogg" (
    echo ɘ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Close-mid_central_unrounded_vowel.ogg' -OutFile '..\assets\sounds\ɘ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɘ.ogg already exists, skipping...
)

echo [66/100] Downloading ɵ...
if not exist "..\assets\sounds\ɵ.ogg" (
    echo ɵ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/5/53/Close-mid_central_rounded_vowel.ogg' -OutFile '..\assets\sounds\ɵ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɵ.ogg already exists, skipping...
)

echo [67/100] Downloading ə...
if not exist "..\assets\sounds\ə.ogg" (
    echo ə.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Schwa.ogg' -OutFile '..\assets\sounds\ə.ogg' -TimeoutSec 30"
) else (
    echo ✓ ə.ogg already exists, skipping...
)

echo [68/100] Downloading ɜ...
if not exist "..\assets\sounds\ɜ.ogg" (
    echo ɜ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Open-mid_central_unrounded_vowel.ogg' -OutFile '..\assets\sounds\ɜ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɜ.ogg already exists, skipping...
)

echo [69/100] Downloading ɞ...
if not exist "..\assets\sounds\ɞ.ogg" (
    echo ɞ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/0/00/Open-mid_central_rounded_vowel.ogg' -OutFile '..\assets\sounds\ɞ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɞ.ogg already exists, skipping...
)

echo [70/100] Downloading ɐ...
if not exist "..\assets\sounds\ɐ.ogg" (
    echo ɐ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/4/49/Near-open_central_vowel.ogg' -OutFile '..\assets\sounds\ɐ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɐ.ogg already exists, skipping...
)

REM Back Vowels
echo [71/100] Downloading ɯ...
if not exist "..\assets\sounds\ɯ.ogg" (
    echo ɯ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Close_back_unrounded_vowel.ogg' -OutFile '..\assets\sounds\ɯ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɯ.ogg already exists, skipping...
)

echo [72/100] Downloading u...
if not exist "..\assets\sounds\u.ogg" (
    echo u.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/5/5d/Close_back_rounded_vowel.ogg' -OutFile '..\assets\sounds\u.ogg' -TimeoutSec 30"
) else (
    echo ✓ u.ogg already exists, skipping...
)

echo [73/100] Downloading ʊ...
if not exist "..\assets\sounds\ʊ.ogg" (
    echo ʊ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/7/7f/Near-close_back_rounded_vowel.ogg' -OutFile '..\assets\sounds\ʊ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʊ.ogg already exists, skipping...
)

echo [74/100] Downloading o...
if not exist "..\assets\sounds\o.ogg" (
    echo o.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/8/84/Close-mid_back_rounded_vowel.ogg' -OutFile '..\assets\sounds\o.ogg' -TimeoutSec 30"
) else (
    echo ✓ o.ogg already exists, skipping...
)

echo [75/100] Downloading ɤ...
if not exist "..\assets\sounds\ɤ.ogg" (
    echo ɤ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Close-mid_back_unrounded_vowel.ogg' -OutFile '..\assets\sounds\ɤ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɤ.ogg already exists, skipping...
)

echo [76/100] Downloading ɔ...
if not exist "..\assets\sounds\ɔ.ogg" (
    echo ɔ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Open-mid_back_rounded_vowel.ogg' -OutFile '..\assets\sounds\ɔ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɔ.ogg already exists, skipping...
)

echo [77/100] Downloading ʌ...
if not exist "..\assets\sounds\ʌ.ogg" (
    echo ʌ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Open-mid_back_unrounded_vowel.ogg' -OutFile '..\assets\sounds\ʌ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʌ.ogg already exists, skipping...
)

echo [78/100] Downloading ɑ...
if not exist "..\assets\sounds\ɑ.ogg" (
    echo ɑ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Open_back_unrounded_vowel.ogg' -OutFile '..\assets\sounds\ɑ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɑ.ogg already exists, skipping...
)

echo [79/100] Downloading ɒ...
if not exist "..\assets\sounds\ɒ.ogg" (
    echo ɒ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Open_back_rounded_vowel.ogg' -OutFile '..\assets\sounds\ɒ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɒ.ogg already exists, skipping...
)

echo.
echo Downloading Additional Symbols...

REM Affricates
echo [80/100] Downloading t͡s...
if not exist "..\assets\sounds\t͡s.ogg" (
    echo t͡s.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/9/9d/Voiceless_alveolar_sibilant_affricate.ogg' -OutFile '..\assets\sounds\t͡s.ogg' -TimeoutSec 30"
) else (
    echo ✓ t͡s.ogg already exists, skipping...
)

echo [81/100] Downloading d͡z...
if not exist "..\assets\sounds\d͡z.ogg" (
    echo d͡z.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/d/d8/Voiced_alveolar_sibilant_affricate.ogg' -OutFile '..\assets\sounds\d͡z.ogg' -TimeoutSec 30"
) else (
    echo ✓ d͡z.ogg already exists, skipping...
)

echo [82/100] Downloading t͡ʃ...
if not exist "..\assets\sounds\t͡ʃ.ogg" (
    echo t͡ʃ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/9/97/Voiceless_palato-alveolar_affricate.ogg' -OutFile '..\assets\sounds\t͡ʃ.ogg' -TimeoutSec 30"
) else (
    echo ✓ t͡ʃ.ogg already exists, skipping...
)

echo [83/100] Downloading d͡ʒ...
if not exist "..\assets\sounds\d͡ʒ.ogg" (
    echo d͡ʒ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/e/e6/Voiced_palato-alveolar_affricate.ogg' -OutFile '..\assets\sounds\d͡ʒ.ogg' -TimeoutSec 30"
) else (
    echo ✓ d͡ʒ.ogg already exists, skipping...
)

REM Clicks
echo [84/100] Downloading ǀ...
if not exist "..\assets\sounds\ǀ.ogg" (
    echo ǀ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/1/1f/Dental_click.ogg' -OutFile '..\assets\sounds\ǀ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ǀ.ogg already exists, skipping...
)

echo [85/100] Downloading ǁ...
if not exist "..\assets\sounds\ǁ.ogg" (
    echo ǁ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Lateral_click.ogg' -OutFile '..\assets\sounds\ǁ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ǁ.ogg already exists, skipping...
)

echo [86/100] Downloading ǂ...
if not exist "..\assets\sounds\ǂ.ogg" (
    echo ǂ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/4/49/Palatoalveolar_click.ogg' -OutFile '..\assets\sounds\ǂ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ǂ.ogg already exists, skipping...
)

echo [87/100] Downloading ǃ...
if not exist "..\assets\sounds\ǃ.ogg" (
    echo ǃ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Alveolar_click.ogg' -OutFile '..\assets\sounds\ǃ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ǃ.ogg already exists, skipping...
)

REM Implosives
echo [88/100] Downloading ɓ...
if not exist "..\assets\sounds\ɓ.ogg" (
    echo ɓ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Voiced_bilabial_implosive.ogg' -OutFile '..\assets\sounds\ɓ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɓ.ogg already exists, skipping...
)

echo [89/100] Downloading ɗ...
if not exist "..\assets\sounds\ɗ.ogg" (
    echo ɗ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Voiced_alveolar_implosive.ogg' -OutFile '..\assets\sounds\ɗ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɗ.ogg already exists, skipping...
)

echo [90/100] Downloading ʄ...
if not exist "..\assets\sounds\ʄ.ogg" (
    echo ʄ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Voiced_palatal_implosive.ogg' -OutFile '..\assets\sounds\ʄ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʄ.ogg already exists, skipping...
)

echo [91/100] Downloading ɠ...
if not exist "..\assets\sounds\ɠ.ogg" (
    echo ɠ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Voiced_velar_implosive.ogg' -OutFile '..\assets\sounds\ɠ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɠ.ogg already exists, skipping...
)

echo [92/100] Downloading ʛ...
if not exist "..\assets\sounds\ʛ.ogg" (
    echo ʛ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Voiced_uvular_implosive.ogg' -OutFile '..\assets\sounds\ʛ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʛ.ogg already exists, skipping...
)

REM Ejectives
echo [93/100] Downloading pʼ...
if not exist "..\assets\sounds\pʼ.ogg" (
    echo pʼ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Bilabial_ejective.ogg' -OutFile '..\assets\sounds\pʼ.ogg' -TimeoutSec 30"
) else (
    echo ✓ pʼ.ogg already exists, skipping...
)

echo [94/100] Downloading tʼ...
if not exist "..\assets\sounds\tʼ.ogg" (
    echo tʼ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Alveolar_ejective.ogg' -OutFile '..\assets\sounds\tʼ.ogg' -TimeoutSec 30"
) else (
    echo ✓ tʼ.ogg already exists, skipping...
)

echo [95/100] Downloading kʼ...
if not exist "..\assets\sounds\kʼ.ogg" (
    echo kʼ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Velar_ejective.ogg' -OutFile '..\assets\sounds\kʼ.ogg' -TimeoutSec 30"
) else (
    echo ✓ kʼ.ogg already exists, skipping...
)

echo [96/100] Downloading sʼ...
if not exist "..\assets\sounds\sʼ.ogg" (
    echo sʼ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Alveolar_ejective_fricative.ogg' -OutFile '..\assets\sounds\sʼ.ogg' -TimeoutSec 30"
) else (
    echo ✓ sʼ.ogg already exists, skipping...
)

echo [97/100] Downloading ɬʼ...
if not exist "..\assets\sounds\ɬʼ.ogg" (
    echo ɬʼ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Alveolar_lateral_ejective_fricative.ogg' -OutFile '..\assets\sounds\ɬʼ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɬʼ.ogg already exists, skipping...
)

REM Additional Common Sounds
echo [98/100] Downloading w...
if not exist "..\assets\sounds\w.ogg" (
    echo w.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/f/f2/Voiced_labio-velar_approximant.ogg' -OutFile '..\assets\sounds\w.ogg' -TimeoutSec 30"
) else (
    echo ✓ w.ogg already exists, skipping...
)

echo [99/100] Downloading ɥ...
if not exist "..\assets\sounds\ɥ.ogg" (
    echo ɥ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Voiceless_labial-palatal_approximant.ogg' -OutFile '..\assets\sounds\ɥ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ɥ.ogg already exists, skipping...
)

echo [100/100] Downloading ʍ...
if not exist "..\assets\sounds\ʍ.ogg" (
    echo ʍ.ogg not found, downloading...
    powershell -Command "Start-Sleep -Seconds 120; Invoke-WebRequest -Uri 'http://upload.wikimedia.org/wikipedia/commons/6/6c/Voiceless_labial-velar_approximant.ogg' -OutFile '..\assets\sounds\ʍ.ogg' -TimeoutSec 30"
) else (
    echo ✓ ʍ.ogg already exists, skipping...
)

echo.
echo Download completed!
echo Generated comprehensive IPA sound mapping file...

(
echo // Complete IPA Symbol to Sound File Mapping
echo // Generated from Wikipedia International Phonetic Alphabet
echo.
echo const ipaSoundMapping = {
echo     // Pulmonic Consonants
echo     'p': 'assets/sounds/p.ogg', 'b': 'assets/sounds/b.ogg', 't': 'assets/sounds/t.ogg', 'd': 'assets/sounds/d.ogg',
echo     'k': 'assets/sounds/k.ogg', 'g': 'assets/sounds/g.ogg', 'q': 'assets/sounds/q.ogg', 'ɢ': 'assets/sounds/ɢ.ogg', 'ʔ': 'assets/sounds/ʔ.ogg',
echo     'm': 'assets/sounds/m.ogg', 'n': 'assets/sounds/n.ogg', 'ŋ': 'assets/sounds/ŋ.ogg',
echo     'ʙ': 'assets/sounds/ʙ.ogg', 'r': 'assets/sounds/r.ogg', 'ʀ': 'assets/sounds/ʀ.ogg',
echo     'ⱱ': 'assets/sounds/ⱱ.ogg', 'ɾ': 'assets/sounds/ɾ.ogg', 'ɽ': 'assets/sounds/ɽ.ogg',
echo     'ɸ': 'assets/sounds/ɸ.ogg', 'β': 'assets/sounds/β.ogg', 'f': 'assets/sounds/f.ogg', 'v': 'assets/sounds/v.ogg',
echo     'θ': 'assets/sounds/θ.ogg', 'ð': 'assets/sounds/ð.ogg', 's': 'assets/sounds/s.ogg', 'z': 'assets/sounds/z.ogg',
echo     'ʃ': 'assets/sounds/ʃ.ogg', 'ʒ': 'assets/sounds/ʒ.ogg', 'ʂ': 'assets/sounds/ʂ.ogg', 'ʐ': 'assets/sounds/ʐ.ogg',
echo     'ç': 'assets/sounds/ç.ogg', 'ʝ': 'assets/sounds/ʝ.ogg', 'x': 'assets/sounds/x.ogg', 'ɣ': 'assets/sounds/ɣ.ogg',
echo     'χ': 'assets/sounds/χ.ogg', 'ʁ': 'assets/sounds/ʁ.ogg', 'ħ': 'assets/sounds/ħ.ogg', 'ʕ': 'assets/sounds/ʕ.ogg',
echo     'h': 'assets/sounds/h.ogg', 'ɦ': 'assets/sounds/ɦ.ogg',
echo     'ɬ': 'assets/sounds/ɬ.ogg', 'ɮ': 'assets/sounds/ɮ.ogg',
echo     'ʋ': 'assets/sounds/ʋ.ogg', 'ɹ': 'assets/sounds/ɹ.ogg', 'ɻ': 'assets/sounds/ɻ.ogg', 'j': 'assets/sounds/j.ogg', 'ɰ': 'assets/sounds/ɰ.ogg',
echo     'l': 'assets/sounds/l.ogg', 'ɭ': 'assets/sounds/ɭ.ogg', 'ʎ': 'assets/sounds/ʎ.ogg', 'ʟ': 'assets/sounds/ʟ.ogg',
echo.
echo     // Vowels
echo     'i': 'assets/sounds/i.ogg', 'y': 'assets/sounds/y.ogg', 'ɨ': 'assets/sounds/ɨ.ogg', 'ʉ': 'assets/sounds/ʉ.ogg', 'ɯ': 'assets/sounds/ɯ.ogg', 'u': 'assets/sounds/u.ogg',
echo     'ɪ': 'assets/sounds/ɪ.ogg', 'ʏ': 'assets/sounds/ʏ.ogg', 'ʊ': 'assets/sounds/ʊ.ogg',
echo     'e': 'assets/sounds/e.ogg', 'ø': 'assets/sounds/ø.ogg', 'ɘ': 'assets/sounds/ɘ.ogg', 'ɵ': 'assets/sounds/ɵ.ogg', 'ɤ': 'assets/sounds/ɤ.ogg', 'o': 'assets/sounds/o.ogg',
echo     'ə': 'assets/sounds/ə.ogg', 'ɜ': 'assets/sounds/ɜ.ogg', 'ɞ': 'assets/sounds/ɞ.ogg',
echo     'ɛ': 'assets/sounds/ɛ.ogg', 'œ': 'assets/sounds/œ.ogg', 'ʌ': 'assets/sounds/ʌ.ogg', 'ɔ': 'assets/sounds/ɔ.ogg',
echo     'æ': 'assets/sounds/æ.ogg', 'ɐ': 'assets/sounds/ɐ.ogg', 'ɶ': 'assets/sounds/ɶ.ogg', 'a': 'assets/sounds/a.ogg', 'ɑ': 'assets/sounds/ɑ.ogg', 'ɒ': 'assets/sounds/ɒ.ogg',
echo.
echo     // Affricates
echo     't͡s': 'assets/sounds/t͡s.ogg', 'd͡z': 'assets/sounds/d͡z.ogg', 't͡ʃ': 'assets/sounds/t͡ʃ.ogg', 'd͡ʒ': 'assets/sounds/d͡ʒ.ogg',
echo.
echo     // Clicks
echo     'ǀ': 'assets/sounds/ǀ.ogg', 'ǁ': 'assets/sounds/ǁ.ogg', 'ǂ': 'assets/sounds/ǂ.ogg', 'ǃ': 'assets/sounds/ǃ.ogg',
echo.
echo     // Implosives
echo     'ɓ': 'assets/sounds/ɓ.ogg', 'ɗ': 'assets/sounds/ɗ.ogg', 'ʄ': 'assets/sounds/ʄ.ogg', 'ɠ': 'assets/sounds/ɠ.ogg', 'ʛ': 'assets/sounds/ʛ.ogg',
echo.
echo     // Ejectives
echo     'pʼ': 'assets/sounds/pʼ.ogg', 'tʼ': 'assets/sounds/tʼ.ogg', 'kʼ': 'assets/sounds/kʼ.ogg', 'sʼ': 'assets/sounds/sʼ.ogg', 'ɬʼ': 'assets/sounds/ɬʼ.ogg',
echo.
echo     // Additional
echo     'w': 'assets/sounds/w.ogg', 'ɥ': 'assets/sounds/ɥ.ogg', 'ʍ': 'assets/sounds/ʍ.ogg'
echo };
echo.
echo if ^(typeof module !== 'undefined' ^&^& module.exports^) {
echo     module.exports = ipaSoundMapping;
echo } else {
echo     window.ipaSoundMapping = ipaSoundMapping;
echo }
) > "..\assets\js\ipa-sounds-mapping.js"

echo Generated mapping file: assets\js\ipa-sounds-mapping.js
echo.
echo Complete! Processed 100 IPA sounds from Wikipedia Commons.
echo Skipped files that already existed.
echo.
pause
